Internal Server Error: /portal/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 84, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 66, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python3.4/dist-packages/django/template/loader.py", line 48, in select_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.4/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.4/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.4/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.4/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.4/dist-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.4/dist-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.4/dist-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.4/dist-packages/django/template/defaulttags.py", line 810, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 603, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 697, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 609, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'with_ref_to_outcome'
[11/Dec/2016 17:53:21] "GET /portal/1 HTTP/1.1" 500 202735
Internal Server Error: /portal/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 84, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 66, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python3.4/dist-packages/django/template/loader.py", line 48, in select_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.4/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.4/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.4/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.4/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.4/dist-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.4/dist-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.4/dist-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.4/dist-packages/django/template/defaulttags.py", line 810, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 603, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 697, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 609, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'with_ref_to_outcome'
[11/Dec/2016 17:53:23] "GET /portal/1 HTTP/1.1" 500 202735
Performing system checks...

System check identified no issues (0 silenced).
December 11, 2016 - 17:53:18
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 11, 2016 - 17:53:48
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
